#! /bin/sh
### BEGIN INIT INFO
# Provides:          webdav-server
# Required-Start:    $network $remote_fs $local_fs
# Required-Stop:     $network $remote_fs $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Stop/start webdav-server
### END INIT INFO

set -e

test -x /usr/sbin/webdav-server || exit 0

. /lib/lsb/init-functions

# If systemd is installed, we never actually get here.
exit 1

